### ISSUE TITLE
Orders for physical products are being set to Complete in Magento

### ISSUE THREAD

**Issue by tejasmi5** [peach-payments/magento-plugin#1]
Reported by a merchant New Balance. 

1) Physical orders are being shown as Cancelled in Magento once a payment has successfully completed. 

2) In Magento, the same transaction then moves into Processing automatically by Magento.

3) In Magento, the same transaction again is moved into Complete automatically without any changes made by the merchant. When looking at the merchant's admin, the timestamp for the status change for Processing and Complete is exactly the same.

We did some testing on our store and it doesn't seem to be an issue, however the merchant continues to see this behavior.

**Comment by niiamar-peach** [comment]
Order notes from two cases where this happened

**First eg.**

May 21, 2019 3:09:07 PM|Complete
Customer Not Notified 
GoMedia Web Hook: Sent, Status: complete State: complete Response: {"system_order":{"sync_order":1,"queue_id":139292711}}
May 21, 2019 3:09:06 PM|Complete
Customer Notified 
May 21, 2019 3:09:06 PM|Processing
Customer Notification Not Applicable 
Registered notification about captured amount of R699.00. Transaction ID: "8acda4a76ada3435016ada8226e614a9".
May 21, 2019 3:08:05 PM|Canceled
Customer Not Notified 
GoMedia Web Hook: Sent, Status: canceled State: canceled Response: {"system_order":{"sync_order":1,"queue_id":139292586}}
May 21, 2019 3:08:05 PM|Canceled
Customer Notification Not Applicable
May 21, 2019 3:08:00 PM|Pending Payment
Customer Not Notified 
GoMedia Web Hook: Sent, Status: pending_payment State: pending_payment Response: {"system_order":{"sync_order":1,"queue_id":139292576}}
May 21, 2019 3:08:00 PM|Pending Payment
Customer Not Notified 
Customer redirected to PeachPayments with total amount due of R699.00
"


**2nd eg**
May 21, 2019 3:40:19 PM|Complete
Customer Not Notified 
GoMedia Web Hook: Sent, Status: complete State: complete Response: {"system_order":{"sync_order":1,"queue_id":139295743}}
May 21, 2019 3:40:18 PM|Complete
Customer Notified 
May 21, 2019 3:40:18 PM|Processing
Customer Notification Not Applicable 
Registered notification about captured amount of R549.00. Transaction ID: "8acda4a16ada3435016ada9ecfb914fa".
May 21, 2019 3:37:47 PM|Canceled
Customer Not Notified 
GoMedia Web Hook: Sent, Status: canceled State: canceled Response: {"system_order":{"sync_order":1,"queue_id":139295533}}
May 21, 2019 3:37:46 PM|Canceled
Customer Notification Not Applicable
May 21, 2019 3:37:42 PM|Pending Payment
Customer Not Notified 
GoMedia Web Hook: Sent, Status: pending_payment State: pending_payment Response: {"system_order":{"sync_order":1,"queue_id":139295501}}
May 21, 2019 3:37:42 PM|Pending Payment
Customer Not Notified 
Customer redirected to PeachPayments with total amount due of R549.00

**Comment by rootindex** [comment]
By reading the attached issue and queue-log, I would suggest the merchant look into any module customisations or 3rd party integrations that might manipulate the order state and status.

On a default Magento instance, I have not been able replicate the outlined behaviour.

**Comment by niiamar-peach** [comment]
Thank you @rootindex - Merchant is investigating this on their side.
