### ISSUE TITLE
Merchants want the option to receive Invoice emails

### ISSUE THREAD

**Issue by tejasmi5** [peach-payments/magento-plugin#2]
Merchant New Balance is requesting an additional feature to have an invoice sent to their order processing. This had been supported in the older plugin that the merchant was using.

**Comment by rootindex** [comment]
The feature request have been completed, I have added two more options in the advanced configuration, namely

- Send Order Email (Default: Yes)
- Send Invoice Email (Default: No)

Please note the order and invoice emails will ONLY be triggered on a successful confirmed order.
