### ISSUE TITLE
Completed Mobicred Payments Are Re-Directed Back to Merchant's Checkout Page

### ISSUE THREAD

**Issue by tejasmi5** [peach-payments/magento-plugin#3]
Issue is isolated to Mobicred transactions.

1. Go through the merchant's checkout page and select Mobicred as the payment method.
2. Complete the Mobicred payment on the Peach Payments Checkout page
3. After a successful payment, user should be re-directed back to the completed payment confirmation page

Observed: User is re-directed back to the merchant checkout page in step 1. 
Expected: User is re-directed back to the merchant's store with a confirmation of the payment.

**Comment by tejasmi5** [comment]
As discussed on Slack - 

Plug-in should check will need to check for completed or canceled state AFTER receiving the notification for a pending payment. 

If the customer cancels then the result code is *100.396.101 "Cancelled by user"*
If the checkout times (ie. 30 minutes lapses without a successful payment) out then the result code is *100.396.104 "Uncertain status - probably cancelled by user"*

**Comment by rootindex** [comment]
I have rewritten the order creation pipeline to follow the following logic.

- If result code is `000.000.000` or `000.100.110` mark order as successful
- If result code is `000.200.000` or `000.200.000` . do not take any action on the order
- Any other status code not mentioned above will result in a cancelled order which will restore the customer quote
